#!/usr/bin/env bash

# Script: tainted-module-manager.sh
# Description: Interactive dialog tool to detect and manage (blacklist) suspicious kernel modules.
# Features:
#   - No need to run with sudo manually (asks when needed)
#   - Scans loaded kernel modules
#   - Flags suspicious modules (vague descriptions, test modules, etc.)
#   - Lets you interactively select modules to blacklist
#   - Writes to /etc/modprobe.d/blacklist-tainted.conf
#   - Offers to update initramfs and reboot
#   - **Always shows a clear summary at the end**

set -euo pipefail

DIALOG=$(which dialog)
if [[ -z "$DIALOG" ]]; then
    echo "❌ 'dialog' is not installed. Please install it first."
    echo "   On Debian/Ubuntu: sudo apt install dialog"
    echo "   On RHEL/Fedora: sudo dnf install dialog"
    exit 1
fi

BLACKLIST_FILE="/etc/modprobe.d/blacklist-tainted.conf"
TMPFILE=$(mktemp)
SELECTED_MODULES=()
SUSPICIOUS_MODULES=()
ANY_BLACKLISTED=false

# --- Run command with sudo ---
run_with_sudo() {
    sudo bash -c "$1"
}

# --- Fetch loaded modules ---
fetch_modules() {
    echo "MODULE_NAME MODULE_SIZE USED_BY DESCRIPTION SUSPICIOUS" > "$TMPFILE"
    for module in $(lsmod | awk 'NR>1 {print $1}'); do
        size=$(grep -E "^$module\s+" /proc/modules 2>/dev/null | awk '{print $2}' || echo "N/A")
        used_by=$(lsmod | awk -v m="$module" '$1 == m {print $3}')
        desc=$(modinfo -F description "$module" 2>/dev/null || echo "No description")
        suspicious=""
        if [[ -z "$desc" ]] || [[ "$desc" == *"test"* ]] || [[ "$desc" == *"debug"* ]] || [[ "$desc" == *"virtual"* ]] || [[ "$desc" == *"vhba"* ]] || [[ ! "$desc" =~ [A-Za-z0-9] ]]; then
            suspicious="[?]"
            SUSPICIOUS_MODULES+=("$module")
        else
            suspicious=""
        fi
        printf "%-20s %-10s %-10s \"%s\" %s\n" "$module" "$size" "$used_by" "$desc" "$suspicious" >> "$TMPFILE"
    done
}

# --- Show module selection dialog ---
show_module_selection() {
    fetch_modules

    exec 3>&1
    MODULE_CHOICES=$(
        awk '
        NR > 1 {
            gsub(/"/, "\\\"", $4);
            printf "%s \"%s\" \"%s\"\n", $1, $4, $5
        }' "$TMPFILE" \
        | dialog --title "🔍 Loaded Kernel Modules" \
                 --checklist "Select modules to blacklist (marked [?] may be suspicious)\n\
(Use arrows, Space to toggle, Enter to confirm):" 25 80 15 \
                 2>&1 1>&3
    )
    exec 3>&-

    if [[ -z "$MODULE_CHOICES" ]]; then
        echo "ℹ️  No modules selected by user."
    else
        IFS='|' read -ra SELECTED_MODULES <<< "$MODULE_CHOICES"
        ANY_BLACKLISTED=true
    fi
}

# --- Apply blacklist and offer updates ---
apply_blacklist() {
    if [[ ${#SELECTED_MODULES[@]} -eq 0 ]]; then
        return
    fi

    {
        echo "# ===== Auto-generated by tainted-module-manager on $(date) ====="
        echo "# "
    } > "$BLACKLIST_FILE"

    for module in "${SELECTED_MODULES[@]}"; do
        echo "blacklist $module" >> "$BLACKLIST_FILE"
        echo "# Disabled by user request." >> "$BLACKLIST_FILE"
    done

    {
        echo "# ==============================================================="
    } >> "$BLACKLIST_FILE"

    echo "✅ Blacklist saved to: $BLACKLIST_FILE"

    # Offer to update initramfs
    exec 3>&1
    update_choice=$(dialog --title "🔄 Initramfs Update" \
        --yesno "Update initramfs? (Recommended if modules load early)" 10 60 3>&1 1>&2 2>&3)
    exec 3>&-

    if [[ "$update_choice" == 0 ]]; then
        echo "🛠️  Updating initramfs..."
        if command -v update-initramfs &> /dev/null; then
            run_with_sudo "update-initramfs -u"
        elif command -v dracut &> /dev/null; then
            run_with_sudo "dracut --force"
        else
            echo "⚠️  Neither update-initramfs nor dracut found. Skipping."
        fi
    fi

    # Offer to reboot
    exec 3>&1
    reboot_choice=$(dialog --title "🚀 Reboot?" \
        --yesno "Reboot system now?" 10 50 3>&1 1>&2 2>&3)
    exec 3>&-

    if [[ "$reboot_choice" == 0 ]]; then
        echo "🔁 Rebooting system..."
        run_with_sudo "reboot"
    fi

    ANY_BLACKLISTED=true
}

# ------- MAIN FLOW -------

# Intro (optional, stderr)
{
    echo "🔐 This script will ask for sudo password when needed."
    echo "🔍 It scans your kernel modules. You choose what to blacklist."
} >&2

# Fetch and show modules
show_module_selection

# Apply blacklist if any
apply_blacklist

# --- ALWAYS SHOW FINAL SUMMARY DIALOG ---
exec 3>&1
{
    summary=""

    if [[ "$ANY_BLACKLISTED" == true ]]; then
        summary+="✅ The following modules were blacklisted:\n"
        for m in "${SELECTED_MODULES[@]}"; do
            summary+="   • $m\n"
        done
        summary+="\n"
    else
        summary+="ℹ️  No modules were selected for blacklisting.\n\n"
    fi

    if [[ ${#SUSPICIOUS_MODULES[@]} -gt 0 ]]; then
        summary+="⚠️  The following modules were auto-detected as potentially suspicious:\n"
        for m in "${SUSPICIOUS_MODULES[@]}"; do
            desc=$(modinfo -F description "$m" 2>/dev/null || echo 'No description')
            summary+="   • $m (Description: \"$desc\")\n"
        done
        summary+="\nℹ️  You can select them next time to blacklist them.\n\n"
    else
        summary+="✅ No suspicious modules were auto-detected.\n\n"
    fi

    if [[ "$ANY_BLACKLISTED" == false && ${#SUSPICIOUS_MODULES[@]} -eq 0 ]]; then
        summary+="🟢 System is clean: No tainted or suspicious modules detected or blacklisted.\n"
    fi

    echo -e "$summary"
} | dialog --title "📋 Operation Complete" \
    --msgbox "$(cat)" 22 70 3>&1 1>&2 2>&3
exec 3>&-

# Cleanup
rm -f "$TMPFILE"
echo "🎉 Done. Blacklist file (if any): $BLACKLIST_FILE"
